/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApiSelect: typeof import('./../src/components/Form/components/ApiSelect.vue')['default']
    BasicArrow: typeof import('./../src/components/Basic/src/BasicArrow.vue')['default']
    BasicForm: typeof import('./../src/components/Form/BasicForm.vue')['default']
    BasicHelp: typeof import('./../src/components/Basic/src/BasicHelp.vue')['default']
    BasicTable: typeof import('./../src/components/Table/BasicTable.vue')['default']
    BasicTitle: typeof import('./../src/components/Basic/src/BasicTitle.vue')['default']
    CheckboxGroup: typeof import('./../src/components/Form/components/CheckboxGroup.vue')['default']
    ColumnSetting: typeof import('./../src/components/Table/components/settings/ColumnSetting.vue')['default']
    EditableCell: typeof import('./../src/components/Table/components/editable/EditableCell.vue')['default']
    EditTableHeaderIcon: typeof import('./../src/components/Table/components/EditTableHeaderIcon.vue')['default']
    FormAction: typeof import('./../src/components/Form/components/FormAction.vue')['default']
    FormItem: typeof import('./../src/components/Form/components/FormItem.vue')['default']
    FullScreenSetting: typeof import('./../src/components/Table/components/settings/FullScreenSetting.vue')['default']
    HeaderCell: typeof import('./../src/components/Table/components/HeaderCell.vue')['default']
    InnerTableColumn: typeof import('./../src/components/Table/components/InnerTableColumn.vue')['default']
    Pagination: typeof import('./../src/components/Table/components/Pagination.vue')['default']
    RadioGroup: typeof import('./../src/components/Form/components/RadioGroup.vue')['default']
    RedoSetting: typeof import('./../src/components/Table/components/settings/RedoSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../src/components/Table/components/settings/index.vue')['default']
    SizeSetting: typeof import('./../src/components/Table/components/settings/SizeSetting.vue')['default']
    TableAction: typeof import('./../src/components/Table/components/TableAction.vue')['default']
    TableHeader: typeof import('./../src/components/Table/components/TableHeader.vue')['default']
    TableImg: typeof import('./../src/components/Table/components/TableImg.vue')['default']
    TableTitle: typeof import('./../src/components/Table/components/TableTitle.vue')['default']
  }
}
