// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApiSelect: typeof import('./../src/components/Form/src/components/ApiSelect.vue')['default']
    BasicArrow: typeof import('./../src/components/Basic/src/BasicArrow.vue')['default']
    BasicForm: typeof import('./../src/components/Form/src/BasicForm.vue')['default']
    BasicHelp: typeof import('./../src/components/Basic/src/BasicHelp.vue')['default']
    BasicTitle: typeof import('./../src/components/Basic/src/BasicTitle.vue')['default']
    CheckboxGroup: typeof import('./../src/components/Form/src/components/CheckboxGroup.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormAction: typeof import('./../src/components/Form/src/components/FormAction.vue')['default']
    FormItem: typeof import('./../src/components/Form/src/components/FormItem.vue')['default']
    RadioGroup: typeof import('./../src/components/Form/src/components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
